# Comment to be posted to on PRs from first time contributors in your repository
newPRWelcomeComment: |
  ğŸ’– Thanks for opening this pull request! ğŸ’–

  Things that will help get your PR across the finish line:

  - Follow the TypeScript [coding style](https://github.com/rrweb-io/rrweb/blob/master/docs/development/coding-style.md).
  - Run `yarn lint` locally to catch formatting errors earlier.
  - Document any user-facing changes you've made following the [documentation styleguide](https://github.com/rrweb-io/rrweb/blob/master/blob/main/docs/styleguide.md).
  - Include tests when adding/changing behavior.
  - Include screenshots and animated GIFs whenever possible.

  We get a lot of pull requests on this repo, so please be patient and we will get back to you as soon as we can.

# Configuration for first-pr-merge - https://github.com/behaviorbot/first-pr-merge

# Comment to be posted to on pull requests merged by a first time user
firstPRMergeComment: >
  Congrats on merging your first pull request! ğŸ‰ğŸ‰ğŸ‰Hallo
